import { Urbanist, Dancing_Script } from "next/font/google";
import "./globals.css";
import { Analytics } from "@vercel/analytics/next";

const getUrbanist = Urbanist({
  variable: "--font-urbanist",
  subsets: ["latin"],
});

const getDancingScript = Dancing_Script({
  variable: "--font-dancing-script",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${getUrbanist.variable} ${getDancingScript.variable} antialiased`}>
        {children}
        <Analytics />
      </body>
    </html>
  );
}
