import { Urbanist, Libre_Baskerville } from "next/font/google";
import "./globals.css";

const getUrbansit = Urbanist({
  variable: "--font-urbanist",
  subsets: ["latin"],
});

const getLibreBaskerville = Libre_Baskerville({
  variable: "--font-libre-baskerville",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${getUrbansit.variable} ${getLibreBaskerville.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
